apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: semantic-searcher

secretGenerator:
- name: envsecrets
  envs:
  - env.txt

configMapGenerator:
- name: chromaprops
  literals:
  - CHROMA_HOST=semantic-searcher-chroma.semantic-searcher.svc.cluster.local
  - CHROMA_PORT=8000
  - OPENAI_MODEL_NAME=text-embedding-ada-002

configMapGenerator:
- name: dbprops
  literals:
  - DB_HOST=semantic-searcher-database.semantic-searcher.svc.cluster.local
  - DB_PORT=5432

commonLabels:
  app-project: semantic-searcher

resources:
  - chroma.yaml
  - database.yaml
  - app.yaml
